name: Build, Test and Deploy Zomato Clone

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # ----- BACKEND TEST -----
    - name: Install backend dependencies
      working-directory: ./server
      run: npm install

    - name: Run backend tests
      working-directory: ./server
      run: npm test || echo "⚠️ Backend tests failed"

    # ----- FRONTEND BUILD -----
    - name: Install frontend dependencies
      working-directory: ./client
      run: npm install

    - name: Build frontend
      working-directory: ./client
      run: npm run build

    # ----- DEPLOY TO GCP -----
    - name: Deploy to GCP VM
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.GCP_VM_IP }}
        username: ${{ secrets.GCP_VM_USER }}
        key: ${{ secrets.GCP_SSH_KEY }}
        script: |
          cd zomato-clone-app

          echo "Pulling latest changes..."
          git pull origin main

          echo "Rebuilding and restarting Docker Compose..."
          docker compose down
          docker compose up -d --build
