name: Build, Test and Deploy Zomato Clone

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # ----- BACKEND TEST -----
    - name: Install backend dependencies
      working-directory: ./server
      run: npm install

    - name: Run backend tests
      working-directory: ./server
      run: npm test || echo "⚠️ Backend tests failed"

    # ----- FRONTEND BUILD -----
    - name: Install frontend dependencies
      working-directory: ./client
      run: npm install

    - name: Build front
