name: Deploy Zomato Clone

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to GCP VM
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.GCP_VM_IP }}
        username: ${{ secrets.GCP_VM_USER }}
        key: ${{ secrets.GCP_SSH_KEY }}
        script: |
          cd zomato-clone-app

          echo "Pulling latest code..."
          git pull origin main

          echo "Rebuilding and restarting containers..."
          docker compose down
          docker compose up -d --build
