name: MERN Zomato CI/CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Frontend and Install Backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build React Frontend
        working-directory: client
        run: |
          npm install
          npm run build

      - name: Install Backend Dependencies
        working-directory: server
        run: npm install

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fullstack-build
          path: |
            client/dist
            server
            nginx/default.conf

  test:
    runs-on: ubuntu-latest
    needs: build
    name: Test Backend

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        working-directory: server
        run: npm install

      - name: Run Tests
        working-directory: server
        env:
          MONGODB_URI: mongodb://localhost:27017/testdb
        run: npm test || echo "No tests defined"

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    name: Deploy to Server via SSH

    steps:
      - name: Download Build
        uses: actions/download-artifact@v4
        with:
          name: fullstack-build

      - name: Deploy to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
         
         

      - name: Run Remote Commands (Restart PM2 or NGINX)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo cp ${{ secrets.TARGET_PATH }}/nginx/default.conf /etc/nginx/sites-available/default
            sudo nginx -t && sudo systemctl restart nginx
            cd ${{ secrets.TARGET_PATH }}/server
            npm install
            pm2 restart all || pm2 start index.js --name zomato-backend
