name: Zomato Clone - MERN CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    name: Build & Test React Frontend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Build React App
        run: npm run build

      - name: Run Lint/Test (optional)
        run: |
          echo "No frontend tests defined. Skipping."

  backend:
    name: Test Node Backend with MongoDB
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Set Environment Variables
        run: |
          echo "PORT=4000" >> .env
          echo "MONGODB_URI=mongodb://localhost:27017/zomato-test" >> .env

      - name: Run Backend Tests
        env:
          MONGODB_URI: mongodb://localhost:27017/zomato-test
        run: |
          echo "No test script defined. Skipping tests."
          # npm test
